CREATE TABLE IF NOT EXISTS statistics (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  app VARCHAR(40) NOT NULL,
  uri VARCHAR(40) NOT NULL,
  ip VARCHAR(40) NOT NULL,
  data TIMESTAMP NOT NULL
);