version: '3.1'
services:
  stats-server:
    build: ./stats/service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/exploreWithMe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot


  stats-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=exploreWithMe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot


  ewm-service:
    build: ./ewmService/
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db

    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmService
      - SPRING.DATASOURCE.USERNAME=postgres
      - SPRING.DATASOURCE.PASSWORD=iamroot
    image: ewm_service
    container_name: ewm-service

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmService
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

